{{- if eq (include "greenmedical.secret.create" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenmedical.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenmedical.backend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.database.url }}
  DATABASE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.adminToken.value }}
  ADMIN_TOKEN: {{ . | quote }}
  {{- end }}
{{- end }}
