{{- $sm := .Values.metrics.serviceMonitor -}}
{{- if $sm.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "greenmedical.backend.fullname" . }}
  namespace: {{ $sm.namespace | default .Release.Namespace }}
  labels:
    {{- include "greenmedical.backend.labels" . | nindent 4 }}
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations $sm.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $sm.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "greenmedical.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: {{ $sm.interval }}
      scrapeTimeout: {{ $sm.scrapeTimeout }}
      honorLabels: {{ $sm.honorLabels }}
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
