{{- $replicas := include "greenmedical.replicas" .Values.frontend | int -}}
{{- if and .Values.frontend.podDisruptionBudget.enabled (gt $replicas 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "greenmedical.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greenmedical.frontend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- include "greenmedical.pdb.spec" .Values.frontend | trim | nindent 2 }}
  selector:
    matchLabels:
      {{- include "greenmedical.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
